### PR TITLE
Feature/add mask expansion

### PR DESCRIPTION
**Pull request by jordan-barrett-jm**
Expanding the mask can reduce visual errors as most times there is a slight outline left from the mask created by SAM. With this new feature, users can tweak how much they want to expand that mask through the use of a slider.

### CODE REVIEW

**Comment by jordan-barrett-jm** [comment]
> Thank you for your PR, this feature seems really cool.
> 
> However, I'd suggest replace your `dilate_mask` function as something like this as it will be significantly more efficient when dilation amount is large (8* more efficient when the dilation amount is 100).
> 
> ```
> def dilate_mask(mask, dilation_amt):
>     # Create a dilation kernel
>     x, y = np.meshgrid(np.arange(dilation_amt), np.arange(dilation_amt))
>     center = dilation_amt // 2
>     dilation_kernel = ((x - center)**2 + (y - center)**2 <= center**2).astype(np.uint8)
> 
>     # Dilate the image
>     dilated_binary_img = binary_dilation(mask, dilation_kernel)
> 
>     # Convert the dilated binary numpy array back to a PIL image
>     dilated_mask = Image.fromarray(np.uint8(dilated_binary_img) * 255)
> 
>     return dilated_mask
> ```
> 
> Another suggestion is that this feature could be separate: there is no need to expand mask before the user really sees the segmentation result, but re-generate will take more time for the user. It would be better if the worfflow could be like this:
> 
> 1. user sees the segmentation and choose the best
> 2. user choose whether to adjust the mask and if so, the user adjust the mask and preview the mask
> 3. repeat 2 when the user is satisfied
> 4. send the final image and mask to process().
> 
> I'd appreciate if you can work on this second suggestion, but if you don't have time, I can do that.
> 
> Thank you very much for your contribution!

Hi, agreed! Thank you for the improvement to the dilation function I will implement it as soon as. I also agree with the flow you mention and I think it already exists. Let me explain - by default, the slider is 0 and as such there will be no dilation applied. As such the flow that currently is in place pretty much aligns with your suggestion. They can see if they want to expand the mask area on the first iteration and if they do then they  simply adjust the slider.

**Comment by continue-revolution** [comment]
The main issue is that it seems that your implementation re-run machine learning inference everytime the user adjusts the dilation. I think it would be much better if the user does not have to re-run machine learning inference everytime.

**Comment by jordan-barrett-jm** [comment]
Good point. I'll adjust

**Comment by jordan-barrett-jm** [comment]
I added a button that allows for the mask to be updated without the need for additional SAM inference. Let me know if this looks good to you

**Comment by continue-revolution** [comment]
1. It seems that you did not update mask on the original image. I mean the first 3 images which display the original image+mask
2. I don't think it is necessary to do mask expansion when you are running ML. It makes more sense to me if you run mask expansion after doing ML. I think it might be better if you remove mask expansion functionality in the ML function.
3. I would propose adding another gallery as output of mask expansion for user to compare the expanded mask result with the original output of SAM. What do you think about this idea? I think this new gallery can just print the user selected mask, instead of all 3.

**Comment by jordan-barrett-jm** [comment]
1. I don't believe the same dilate method would work on the blended image
2. I could remove it, I guess. I don't think it hurts though, especially if the user wants to, say, reduce the mask after it's been expanded.
3. I thought of something similar but the main gripes I had were with the amount of space it would take up and the fact it would involve more steps for the user (like having to select whether or not they want to use the expanded mask). Are you envisioning the expanded mask being what is automatically passed to the process function?

**Comment by continue-revolution** [comment]
1. you can read the input image and re-apply new mask I think.
2. make sense. no need to remove.
3. 
> I thought of something similar but the main gripes I had were with the amount of space it would take up and the fact it would involve more steps for the user (like having to select whether or not they want to use the expanded mask). 

Maybe if the user does not click the button to expand mask, then just use the original gallery; otherwise use the new gallery. Not sure whether it is possible. 

>Are you envisioning the expanded mask being what is automatically passed to the process function?

Yes

**Comment by jordan-barrett-jm** [comment]
Ok on item 3 I can implement this but it might change the structure of the process function that calls the img2img SD module. Would this affect your GroundingDINO implementation? Would you prefer this be merged as-is before I alter that structure?

**Comment by continue-revolution** [comment]
You may just go ahead and I'll take care of this. Thanks again for working on this nice feature.

**Comment by continue-revolution** [comment]
Thank you very much. It seems great to me. After a sleep I will make some small modification and merge.

**Pull request merged**
